package blazarapp

import (
	"net/http"

	"github.com/go-app-blazar/blazar/blazarplugin"
	"github.com/maxence-charriere/go-app/v11/pkg/app"
)

// App is a wrapper around go-app app.Handler that provides a way to add plugins and handle requests.
type App struct {
	appHandler *app.Handler
	mux        *http.ServeMux
	plugins    []blazarplugin.Plugin
}

var _ http.Handler = (*App)(nil)

type Config struct {
	// Name specifies the display name of the web app, used where space permits.
	Name string

	// ShortName is an abbreviated app name for limited display areas.
	ShortName string

	// Icon represents the app icon used for PWA, favicon, and the default
	// "not found" component. Attributes like crossorigin can be appended after
	// a space.
	Icon app.Icon

	// BackgroundColor sets a placeholder background color for the app page
	// before stylesheets load. Defaults to "#2d2c2c".
	BackgroundColor string

	// ThemeColor specifies the app's theme color, affecting OS-level UI elements
	// like the PWA title bar. Defaults to "#2d2c2c".
	ThemeColor string

	// LoadingLabel shows text during page load, with "{progress}" for progress.
	// Defaults to "{progress}%".
	LoadingLabel string

	// Lang defines the primary language of the app page. Defaults to "en".
	Lang string

	// Libraries are custom libraries to load with the page.
	Libraries []app.Library

	// Title sets the title of the app page.
	Title string

	// Description provides a summary of the page's content, used as default
	// meta description and og:description.
	Description string

	// Domain specifies the domain name for resolving page metadata like
	// 'og:url'.
	Domain string

	// Author lists the authors of the page.
	Author string

	// Keywords are words or phrases associated with the page.
	Keywords []string

	// Image specifies the default image path used by social networks.
	// Attributes like crossorigin can be appended after a space.
	Image string

	// Styles lists CSS files for the page, supporting local and external
	// resources. Attributes like crossorigin can be appended after a space.
	Styles []string

	// Fonts lists font files to preload, improving performance and visual
	// readiness. Attributes like crossorigin can be appended after a space.
	Fonts []string

	// Scripts lists JavaScript files for the page. Attributes like crossorigin,
	// async, and defer can be appended, separated with a space.
	Scripts []string

	// CacheableResources specifies extra static resources to cache for offline
	// access. Icon, Styles and Scripts are already cached by default.
	// Attributes like crossorigin can be appended after a space.
	CacheableResources []string

	// RawHeaders contains extra HTML headers for the page's <head> section.
	RawHeaders []string

	// HTML returns the page's HTML element. Defaults to app.Html().
	HTML func() app.HTMLHtml

	// Body returns the page's body element. Defaults to app.Body().
	Body func() app.HTMLBody

	// Env passes environment variables to the PWA. Note: Reserved keys
	// (GOAPP_VERSION, GOAPP_GOAPP_STATIC_RESOURCES_URL) cannot be
	// overridden and are used for internal configuration.
	Env map[string]string

	// InternalURLs lists URLs to open within the app, overriding default behavior
	// for external domains.
	InternalURLs []string

	// Preconnect specifies origins to preconnect to, speeding up future loads.
	// Attributes like crossorigin can be appended after a space.
	Preconnect []string

	// ProxyResources maps custom paths to static resources. /robots.txt,
	// /sitemap.xml, and /ads.txt, which are proxied by default.
	ProxyResources []app.ProxyResource

	// Resources resolves paths for static resources, specifically handling
	// paths prefixed with "/web/". Defaults to app.LocalDir("").
	Resources app.ResourceResolver

	// StartURL defines the initial URL the PWA opens when launched from the
	// home screen or app icon. It should be a relative path (e.g., "/") and
	// typically points to the root of the app. Defaults to "/".
	StartURL string

	// Version defines the app's version. It's crucial for determining if an
	// update is available. Must be set in live environments to avoid recurring
	// updates. Auto-generated by default for local development updates.
	Version string
}

// NewApp creates a new App instance.
func NewApp(config Config) *App {
	mux := http.NewServeMux()

	handler := &app.Handler{
		Name:               config.Name,
		ShortName:          config.ShortName,
		Icon:               config.Icon,
		BackgroundColor:    config.BackgroundColor,
		ThemeColor:         config.ThemeColor,
		LoadingLabel:       config.LoadingLabel,
		Lang:               config.Lang,
		Libraries:          config.Libraries,
		Title:              config.Title,
		Description:        config.Description,
		Domain:             config.Domain,
		Author:             config.Author,
		Keywords:           config.Keywords,
		Image:              config.Image,
		Styles:             config.Styles,
		Fonts:              config.Fonts,
		Scripts:            config.Scripts,
		CacheableResources: config.CacheableResources,
		RawHeaders:         config.RawHeaders,
		HTML:               config.HTML,
		Body:               config.Body,
		Env:                config.Env,
		InternalURLs:       config.InternalURLs,
		Preconnect:         config.Preconnect,
		ProxyResources:     config.ProxyResources,
		Resources:          config.Resources,
		StartURL:           config.StartURL,
		Version:            config.Version,
	}
	mux.Handle("/", handler)

	return &App{
		appHandler: handler,
		mux:        mux,
	}
}

// Handle adds a new handler to the app.
func (a *App) Handle(path string, handler http.Handler) {
	a.mux.Handle(path, handler)
}

// HandleFunc adds a new handler function to the app.
func (a *App) HandleFunc(path string, handler func(http.ResponseWriter, *http.Request)) {
	a.mux.HandleFunc(path, handler)
}

// ServeHTTP serves the app.
func (a *App) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	a.mux.ServeHTTP(w, r)
}

// AddPlugin adds a new plugin to the app.
func (a *App) AddPlugin(plugins ...blazarplugin.Plugin) {
	for _, plugin := range plugins {
		plugin.Register(a.appHandler, a.mux)

		a.plugins = append(a.plugins, plugin)
	}
}

// DisableServiceWorker disables the service worker.
func (a *App) DisableServiceWorker() {
	// Disable the service worker by replacing it with an empty one.
	a.HandleFunc("/app-worker.js", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/javascript")
		w.Write([]byte(""))
	})
}

// GenerateStaticFiles generates the static files for the app.
func (a *App) GenerateStaticFiles() error {
	var pages []string
	for _, page := range a.appHandler.Styles {
		pages = append(pages, page)
	}
	for _, page := range a.appHandler.Scripts {
		pages = append(pages, page)
	}
	for _, page := range a.appHandler.CacheableResources {
		pages = append(pages, page)
	}
	return app.GenerateStaticWebsiteFromMux(".", a.mux, pages...)
}
